In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sn

train = pd.read_csv('../data/train.csv')
test = pd.read_csv('../data/test.csv')
sample_sub = pd.read_csv('../data/sample_submission.csv')

=== SHAPES ===
Train: (577347, 12)
Test: (247435, 11)

=== COLUMNS ===
['id', 'alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'redshift', 'spectral_type', 'galaxy_population', 'class']

=== DTYPES ===
id                     int64
alpha                float64
delta                float64
u                    float64
g                    float64
r                    float64
i                    float64
z                    float64
redshift             float64
spectral_type         object
galaxy_population     object
class                 object
dtype: object

=== MISSING VALUES ===
id                   0
alpha                0
delta                0
u                    0
g                    0
r                    0
i                    0
z                    0
redshift             0
spectral_type        0
galaxy_population    0
class                0
dtype: int64

=== TARGET DISTRIBUTION ===
Target column: class
class
GALAXY    377480
QSO       117143
STAR       82724
Name: count, dtype: int64

=== SAMPLE SUBMISSION FORMAT ===
       id   class
0  577347  GALAXY
1  577348  GALAXY
2  577349  GALAXY
3  577350  GALAXY
4  577351  GALAXY

In [20]:
train.head()

,id,alpha,delta,u,g,r,i,z,redshift,spectral_type,galaxy_population,class
0,0,147.734256,16.959273,25.472123,21.895559,20.357926,19.257113,18.621057,0.408982,M,Red_Sequence,GALAXY
1,1,127.988677,32.346716,20.778509,19.087062,17.587208,17.226067,16.786433,0.157976,M,Red_Sequence,GALAXY
2,2,179.792648,35.344843,21.035203,21.079128,21.171840,20.582629,20.557366,2.823770,O/B,Blue_Cloud,QSO
3,3,225.818295,48.569421,23.305056,21.050736,19.017754,18.365658,17.914952,0.536099,M,Red_Sequence,GALAXY
4,4,141.836135,19.342852,21.703158,19.471680,18.234449,17.899447,17.616185,0.555761,M,Red_Sequence,GALAXY

In [23]:
X_tr = train.drop(columns=['id', 'class'], )
Y_tr = train['class']
X_tr.columns

Index(['alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'redshift', 'spectral_type',
       'galaxy_population'],
      dtype='object')

In [15]:
print("=== SHAPES ===")
print(f"Train: {train.shape}")
print(f"Test: {test.shape}")

=== SHAPES ===
Train: (577347, 12)
Test: (247435, 11)

In [16]:

print("\n=== COLUMNS ===")
print(train.columns.tolist())

print("\n=== DTYPES ===")
print(train.dtypes)

=== COLUMNS ===
['id', 'alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'redshift', 'spectral_type', 'galaxy_population', 'class']

=== DTYPES ===
id                     int64
alpha                float64
delta                float64
u                    float64
g                    float64
r                    float64
i                    float64
z                    float64
redshift             float64
spectral_type         object
galaxy_population     object
class                 object
dtype: object

In [ ]:

print("\n=== MISSING VALUES ===")
print(train.isnull().sum())

print("\n=== TARGET DISTRIBUTION ===")
target_col = sample_sub.columns[1]
print(f"Target column: {target_col}")
print(train[target_col].value_counts())
print(train[target_col].value_counts() / train[target_col].count())

=== MISSING VALUES ===
id                   0
alpha                0
delta                0
u                    0
g                    0
r                    0
i                    0
z                    0
redshift             0
spectral_type        0
galaxy_population    0
class                0
dtype: int64

=== TARGET DISTRIBUTION ===
Target column: class
class
GALAXY    377480
QSO       117143
STAR       82724
Name: count, dtype: int64
class
GALAXY    0.653818
QSO       0.202899
STAR      0.143283
Name: count, dtype: float64

In [33]:
train.iloc[:, 1:].head()

,alpha,delta,u,g,r,i,z,redshift,spectral_type,galaxy_population,class
0,147.734256,16.959273,25.472123,21.895559,20.357926,19.257113,18.621057,0.408982,M,Red_Sequence,GALAXY
1,127.988677,32.346716,20.778509,19.087062,17.587208,17.226067,16.786433,0.157976,M,Red_Sequence,GALAXY
2,179.792648,35.344843,21.035203,21.079128,21.171840,20.582629,20.557366,2.823770,O/B,Blue_Cloud,QSO
3,225.818295,48.569421,23.305056,21.050736,19.017754,18.365658,17.914952,0.536099,M,Red_Sequence,GALAXY
4,141.836135,19.342852,21.703158,19.471680,18.234449,17.899447,17.616185,0.555761,M,Red_Sequence,GALAXY

In [32]:
train.iloc[:, 1:].describe().T

,count,mean,std,min,25%,50%,75%,max
alpha,577347.0,181.616673,96.242941,0.011684,132.161499,188.681465,231.829693,359.999810
delta,577347.0,21.834654,18.933570,-17.966988,2.474097,21.484412,36.988310,79.158322
u,577347.0,22.441926,2.018135,-0.139225,20.977090,22.570222,23.869103,28.253263
g,577347.0,21.007273,1.795426,13.535483,19.865005,21.467820,22.292715,27.620208
r,577347.0,19.962811,1.648964,12.579407,18.820671,20.431153,21.164096,25.254499
i,577347.0,19.378911,1.580059,11.962781,18.306820,19.631642,20.608191,27.910853
z,577347.0,19.041136,1.584365,11.682803,17.973192,19.188598,20.162111,26.826867
redshift,577347.0,0.723135,0.810070,-0.009970,0.181052,0.497525,0.881390,7.010780

In [37]:
train["spectral_type"].unique()

array(['M', 'O/B', 'G/K', 'A/F'], dtype=object)

In [38]:
train["galaxy_population"].unique()

array(['Red_Sequence', 'Blue_Cloud'], dtype=object)

In [39]:
train["class"].unique()

array(['GALAXY', 'QSO', 'STAR'], dtype=object)