## Adding the real SDSS DT for training

The real dataset is missing `galaxy_population` and `spectral_type` feats found in the synth DT. These feats are derivable.

Equation found [here](https://www.kaggle.com/competitions/playground-series-s6e6/discussion/703535)

`spectral_type` = `r - g`

`galaxy_pop` = `u-r`

In [30]:
import pandas as pd
import numpy as np

real_data = pd.read_csv('../data/star_classification(real DT).csv')
data = pd.read_csv('../data/train.csv')

In [ ]:
real_data.head()

,obj_ID,alpha,delta,u,g,r,i,z,run_ID,rerun_ID,cam_col,field_ID,spec_obj_ID,class,redshift,plate,MJD,fiber_ID
0,1.237661e+18,135.689107,32.494632,23.87882,22.27530,20.39501,19.16573,18.79371,3606,301,2,79,6.543777e+18,GALAXY,0.634794,5812,56354,171
1,1.237665e+18,144.826101,31.274185,24.77759,22.83188,22.58444,21.16812,21.61427,4518,301,5,119,1.176014e+19,GALAXY,0.779136,10445,58158,427
2,1.237661e+18,142.188790,35.582444,25.26307,22.66389,20.60976,19.34857,18.94827,3606,301,2,120,5.152200e+18,GALAXY,0.644195,4576,55592,299
3,1.237663e+18,338.741038,-0.402828,22.13682,23.77656,21.61162,20.50454,19.25010,4192,301,3,214,1.030107e+19,GALAXY,0.932346,9149,58039,775
4,1.237680e+18,345.282593,21.183866,19.43718,17.58028,16.49747,15.97711,15.54461,8102,301,3,137,6.891865e+18,GALAXY,0.116123,6121,56187,842

In [9]:
real_data.columns

Index(['obj_ID', 'alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'run_ID',
       'rerun_ID', 'cam_col', 'field_ID', 'spec_obj_ID', 'class', 'redshift',
       'plate', 'MJD', 'fiber_ID'],
      dtype='object')

In [10]:
data.columns

Index(['id', 'alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'redshift',
       'spectral_type', 'galaxy_population', 'class'],
      dtype='object')

In [31]:
unique_to_real_dt = list(set(real_data.columns) - set(data.columns))
unique_to_synth_dt = list(set(data.columns) - set(real_data.columns))
unique_to_real_dt, unique_to_synth_dt

(['field_ID',
  'plate',
  'cam_col',
  'MJD',
  'obj_ID',
  'spec_obj_ID',
  'rerun_ID',
  'run_ID',
  'fiber_ID'],
 ['id', 'spectral_type', 'galaxy_population'])

In [27]:
real_data = real_data.drop(
    columns=['field_ID', 'plate', 'MJD', 'obj_ID',
      'spec_obj_ID', 'rerun_ID', 'run_ID', 'fiber_ID', 'cam_col']
      )

In [23]:
real_data.columns

Index(['alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'class', 'redshift'], dtype='object')

In [ ]:
# WRONG! ASSIGN THE CLASSES.
real_data['spectral_type'] = real_data['r'] - real_data['g']

In [25]:
real_data.head()

,alpha,delta,u,g,r,i,z,class,redshift,spectral_type
0,135.689107,32.494632,23.87882,22.27530,20.39501,19.16573,18.79371,GALAXY,0.634794,-1.88029
1,144.826101,31.274185,24.77759,22.83188,22.58444,21.16812,21.61427,GALAXY,0.779136,-0.24744
2,142.188790,35.582444,25.26307,22.66389,20.60976,19.34857,18.94827,GALAXY,0.644195,-2.05413
3,338.741038,-0.402828,22.13682,23.77656,21.61162,20.50454,19.25010,GALAXY,0.932346,-2.16494
4,345.282593,21.183866,19.43718,17.58028,16.49747,15.97711,15.54461,GALAXY,0.116123,-1.08281